#!/usr/bin/env bash
# First-run setup: writes .env with a generated SECRET_KEY and a UI password.
#
#   ./scripts/bootstrap.sh
#
# Safe to re-run: it refuses to overwrite an existing .env, because replacing
# SECRET_KEY makes every stored MDM credential unreadable.
set -euo pipefail

cd "$(dirname "$0")/.."

if [ -f .env ]; then
  echo ".env already exists - not touching it."
  echo "Delete it yourself if you really mean to start over (you will have to"
  echo "re-enter your MDM credentials, since SECRET_KEY decrypts them)."
  exit 1
fi

if command -v openssl >/dev/null 2>&1; then
  SECRET_KEY=$(openssl rand -hex 32)
elif [ -r /dev/urandom ]; then
  SECRET_KEY=$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')
else
  echo "Need openssl or /dev/urandom to generate a SECRET_KEY." >&2
  exit 1
fi

read -r -p "UI password: " -s ADMIN_PASSWORD; echo
if [ -z "$ADMIN_PASSWORD" ]; then
  echo "A password is required - the UI can lock and wipe devices." >&2
  exit 1
fi

DEFAULT_TZ=UTC
if [ -f /etc/timezone ]; then
  DEFAULT_TZ=$(cat /etc/timezone)
fi
read -r -p "Timezone [$DEFAULT_TZ]: " TZ_INPUT
TZ_VALUE=${TZ_INPUT:-$DEFAULT_TZ}

umask 077
cat > .env <<EOF
# Generated by scripts/bootstrap.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# SECRET_KEY encrypts stored MDM credentials and signs session cookies.
# Back it up with your data volume; changing it orphans stored credentials.
SECRET_KEY=$SECRET_KEY
ADMIN_PASSWORD=$ADMIN_PASSWORD
TZ=$TZ_VALUE

PORT=8000
HTTP_PORT=80
HTTPS_PORT=443
EOF

echo
echo ".env written (mode 600)."
echo
echo "Next:"
echo "  docker compose up -d                              # prebuilt image from GHCR"
echo "  docker compose -f compose.dev.yaml up -d --build   # or build from source"
echo
echo "Then open http://<this-host>:8000 and sign in."
